from __future__ import annotations

from programs.image_generator import orchestrator
from programs.image_generator.providers import image_generation


def test_generate_image_uses_explicit_prompt_without_rebuilding(monkeypatch) -> None:
    captured: dict[str, object] = {}

    def _fail_build(_payload):
        raise AssertionError("build_image_prompt should not run when request already includes a prompt")

    def _fake_generate_images(**kwargs):
        captured.update(kwargs)
        return {
            "id": "pred_test_123",
            "status": "succeeded",
            "output": ["https://example.com/generated.png"],
        }

    monkeypatch.setattr(orchestrator, "build_image_prompt", _fail_build)
    monkeypatch.setattr(image_generation, "generate_images", _fake_generate_images)

    resp = orchestrator.generate_image(
        {
            "instanceId": "instance-123",
            "useCase": "scene",
            "prompt": "Redesign this bathroom with clean tile, warm wood vanity, and matte black fixtures.",
            "negativePrompt": "blurry, low quality",
            "modelId": "black-forest-labs/flux-kontext-pro",
            "numOutputs": 1,
            "referenceImages": ["data:image/jpeg;base64,ZmFrZQ=="],
        }
    )

    assert resp["ok"] is True
    assert captured["prompt"] == "Redesign this bathroom with clean tile, warm wood vanity, and matte black fixtures."
    assert captured["negative_prompt"] == "blurry, low quality"


def test_generate_image_builds_prompt_when_request_prompt_missing(monkeypatch) -> None:
    captured: dict[str, object] = {}

    def _fake_build_image_prompt(_payload):
        return {
            "ok": True,
            "prompt": {
                "prompt": "Generated by DSPy inside the image request.",
                "negativePrompt": "watermark, blurry",
            },
        }

    def _fake_generate_images(**kwargs):
        captured.update(kwargs)
        return {
            "id": "pred_test_456",
            "status": "succeeded",
            "output": ["https://example.com/generated-2.png"],
        }

    monkeypatch.setattr(orchestrator, "build_image_prompt", _fake_build_image_prompt)
    monkeypatch.setattr(image_generation, "generate_images", _fake_generate_images)

    resp = orchestrator.generate_image(
        {
            "instanceId": "instance-456",
            "useCase": "scene",
            "modelId": "black-forest-labs/flux-kontext-pro",
            "numOutputs": 1,
            "referenceImages": ["data:image/jpeg;base64,ZmFrZQ=="],
        }
    )

    assert resp["ok"] is True
    assert captured["prompt"] == "Generated by DSPy inside the image request."
    assert captured["negative_prompt"] == "watermark, blurry"


def test_scene_refinement_inputs_include_previous_prompt_and_refinement_notes() -> None:
    inputs = orchestrator._extract_scene_refinement_inputs(
        {
            "useCase": "scene-refinement",
            "previousPrompt": "Warm transitional bathroom with oak vanity and matte brass hardware.",
            "refinementNotes": "Keep layout exactly the same, but change shower tile to terrazzo and simplify the mirror.",
            "stepDataSoFar": {
                "step-style-direction": ["transitional"],
                "step-budget-range": 35000,
            },
            "instanceContext": {
                "serviceSummary": "Bathroom remodeling service.",
            },
            "sceneImage": "https://example.com/scene.png",
        }
    )

    assert inputs["previous_prompt"] == "Warm transitional bathroom with oak vanity and matte brass hardware."
    assert "terrazzo" in inputs["refinement_notes"].lower()


def test_scene_inputs_budget_tier_shift_uses_broad_regeneration_adherence() -> None:
    inputs = orchestrator._extract_scene_inputs(
        {
            "useCase": "scene",
            "generationIntent": "budget_tier_shift",
            "sceneImage": "https://example.com/scene.png",
            "referenceImages": ["https://example.com/scene.png"],
            "instanceContext": {
                "serviceSummary": "Bathroom remodeling service.",
            },
        }
    )

    assert inputs["generation_intent"] == "budget_tier_shift"
    assert "broad replacement" in inputs["reference_adherence"].lower()
    assert "tiny accessories" in inputs["reference_adherence"].lower()


def test_dspy_inputs_replace_placeholder_service_name_with_inferred_label() -> None:
    out = orchestrator._extract_dspy_inputs(
        {
            "useCase": "scene",
            "instanceContext": {
                "service": {"name": "Service", "id": "00000000-0000-0000-0000-000000000001"},
                "serviceSummary": "Bathroom remodeling is a service that includes new fixtures and tile.",
            },
        }
    )
    assert out["service_name"].lower() != "service"
    assert "bathroom" in out["service_name"].lower()


def test_scene_refinement_inputs_budget_tier_shift_expands_refinement_scope() -> None:
    inputs = orchestrator._extract_scene_refinement_inputs(
        {
            "useCase": "scene-refinement",
            "generationIntent": "budget_tier_shift",
            "refinementNotes": "Increase the finish level and upgrade the vanity and tile.",
            "instanceContext": {
                "serviceSummary": "Bathroom remodeling service.",
            },
            "sceneImage": "https://example.com/scene.png",
        }
    )

    assert inputs["refinement_notes"].lower().startswith("budget tier shift requested.")
    assert "new budget tier" in inputs["reference_adherence"].lower()


def test_fast_schnell_scene_prompt_builds_without_reference(monkeypatch) -> None:
    monkeypatch.delenv("IMAGE_SCENE_USE_DSPY_PROMPT", raising=False)
    payload = {
        "useCase": "scene",
        "modelId": "black-forest-labs/flux-schnell",
        "generationIntent": "initial",
        "instanceContext": {
            "service": {"name": "Bathroom Remodeling"},
            "serviceSummary": "Bathroom remodeling updates fixtures and finishes.",
        },
        "stepDataSoFar": {
            "step-style-direction": "modern_minimal",
            "step-budget-range": 25000,
        },
    }
    assert orchestrator._use_fast_schnell_scene_prompt(payload) is True
    out = orchestrator._build_fast_schnell_scene_prompt(payload, "req_test_fast")
    assert out and out.get("ok") is True
    spec = out.get("prompt") or {}
    assert "bathroom" in str(spec.get("prompt") or "").lower()
    assert spec.get("metadata", {}).get("fastPath") == "schnell_scene"


def test_fast_schnell_scene_prompt_disabled_when_anchor_present(monkeypatch) -> None:
    monkeypatch.delenv("IMAGE_SCENE_USE_DSPY_PROMPT", raising=False)
    payload = {
        "useCase": "scene",
        "modelId": "black-forest-labs/flux-schnell",
        "referenceImages": ["https://example.com/ref.png"],
    }
    assert orchestrator._use_fast_schnell_scene_prompt(payload) is False


def test_fast_schnell_scene_prompt_respects_dspy_env(monkeypatch) -> None:
    monkeypatch.setenv("IMAGE_SCENE_USE_DSPY_PROMPT", "1")
    payload = {
        "useCase": "scene",
        "modelId": "black-forest-labs/flux-schnell",
    }
    assert orchestrator._use_fast_schnell_scene_prompt(payload) is False
