/**
 * Image Prompt Builder
 *
 * Builds deterministic image generation prompts using the TypeScript builder.
 */

import type { ContextState } from "../state/context-state";
import type { PromptState } from "../context/prompt-state";
import { generateDesignerPrompt, prepareDesignerInput, type DesignerInput } from "./designer";

export type ModelRecommendation = {
  modelId?: string;
  guidanceScale?: number;
  numInferenceSteps?: number;
  maxReferenceImages?: number;
  aspectRatio?: string;
  outputFormat?: string;
  promptUpsampling?: boolean;
};

export type ImagePromptResult = {
  prompt: string;
  negativePrompt?: string;
  modelRecommendation?: ModelRecommendation;
  metadata?: {
    confidence?: number;
    completeness?: number;
    styleKeywords?: string[];
    technicalNotes?: string;
  };
  error?: string;
  fromDSPy?: boolean;
};

/**
 * Build an image prompt (deterministic TypeScript builder).
 */
export async function buildImagePromptViaDSPy(params: {
  contextState: ContextState;
  service?: string | null;
  useCase: "tryon" | "scene-placement" | "scene-refinement" | "scene";
  industry?: string | null;
  businessContext?: string | null;
  previousPrompt?: string | null;
  refinementNotes?: string | null;
  steps?: any[];
  stepDataSoFar?: Record<string, any>;
  instanceId?: string;
  sessionId?: string;
  referenceImages?: string[];
  sceneImage?: string | null;
  productImage?: string | null;
  answeredQA?: Array<{ stepId?: string; question?: string; answer?: any }>;
  instanceContext?: Record<string, any> | null;
  generationIntent?: "initial" | "small_improvement" | "regenerate";
  originalReferenceImage?: string | null;
  generationIndex?: number;
}): Promise<ImagePromptResult> {
  const {
    contextState,
    service,
    useCase,
    industry,
    businessContext,
    previousPrompt,
    refinementNotes,
    steps = [],
    stepDataSoFar = {},
    instanceId,
    sessionId,
    referenceImages,
    sceneImage,
    productImage,
    answeredQA,
    instanceContext,
    generationIntent,
    originalReferenceImage,
    generationIndex,
  } = params;

  // Prefer service-generated prompt spec (fast + consistent). Fall back to local deterministic builder.
  try {
    if (instanceId && sessionId) {
      const res = await fetch(`/api/ai-form/${encodeURIComponent(instanceId)}/image-prompt`, {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({
          instanceId,
          sessionId,
          useCase,
          stepDataSoFar,
          referenceImages,
          sceneImage,
          productImage,
          answeredQA,
          instanceContext,
          noCache: typeof window !== "undefined" ? new URLSearchParams(window.location.search).get("fresh") === "1" : undefined,
          ...(generationIntent ? { generationIntent } : {}),
          ...(originalReferenceImage ? { originalReferenceImage } : {}),
          ...(generationIndex !== undefined ? { generationIndex } : {}),
        }),
        cache: "no-store",
      });
      const json = await res.json().catch(() => null);
      const spec = json && typeof json === "object" ? (json as any).prompt : null;
      const prompt = typeof spec?.prompt === "string" ? spec.prompt : null;
      const negativePrompt =
        typeof spec?.negativePrompt === "string"
          ? spec.negativePrompt
          : typeof spec?.negative_prompt === "string"
            ? spec.negative_prompt
            : undefined;
      if (res.ok && prompt && prompt.trim()) {
        const modelRec = spec?.modelRecommendation && typeof spec.modelRecommendation === "object"
          ? spec.modelRecommendation as ModelRecommendation
          : undefined;
        return {
          prompt: prompt.trim(),
          negativePrompt: typeof negativePrompt === "string" && negativePrompt.trim() ? negativePrompt.trim() : undefined,
          modelRecommendation: modelRec,
          metadata: {
            confidence: contextState.confidence,
            completeness: contextState.isComplete ? 1.0 : contextState.confidence,
            technicalNotes: "Generated by api-service (/v1/api/image/prompt)",
          },
          fromDSPy: true,
        };
      }
    }
  } catch {}

  return buildImagePromptFallback({ contextState, service, useCase, industry, businessContext, steps, stepDataSoFar });
}

/**
 * Fallback TypeScript prompt builder (used when DSPy unavailable)
 */
function buildImagePromptFallback(params: {
  contextState: ContextState;
  service?: string | null;
  useCase: "tryon" | "scene-placement" | "scene-refinement" | "scene";
  industry?: string | null;
  businessContext?: string | null;
  steps?: any[];
  stepDataSoFar?: Record<string, any>;
}): ImagePromptResult {
  const {
    contextState,
    service,
    useCase,
    industry,
    businessContext,
    steps = [],
    stepDataSoFar = {},
  } = params;

  // Build designer input from context state
  const designerInput: DesignerInput = {
    businessContext: businessContext || undefined,
    industry: industry || undefined,
    subcategoryName: service || undefined,
    promptState: contextState.promptState,
    preferences: {},
    previousAnswers: {},
  };

  // Extract preferences and answers from context entries
  for (const entry of contextState.entries) {
    const key = entry.stepId.replace(/^step-/, "").replace(/-/g, "_");
    designerInput.previousAnswers![key] = entry.answer;
    
    // Extract style-related preferences
    const questionLower = String((entry as any)?.question || "").toLowerCase();
    if (
      questionLower.includes("style") ||
      questionLower.includes("color") ||
      questionLower.includes("material") ||
      questionLower.includes("preference") ||
      questionLower.includes("design")
    ) {
      designerInput.preferences![key] = entry.answer;
    }
  }

  // Generate prompt using existing TypeScript builder
  const prompt = generateDesignerPrompt(designerInput);

  // Build negative prompt from exclusions
  const negativePromptParts: string[] = [];
  if (contextState.promptState.exclusions && contextState.promptState.exclusions.length > 0) {
    for (const exclusion of contextState.promptState.exclusions.slice(0, 5)) {
      negativePromptParts.push(String(exclusion.value));
    }
  }
  const negativePrompt = negativePromptParts.join(", ");

  // Extract style keywords from context
  const styleKeywords: string[] = [];
  for (const entry of contextState.entries) {
    if (typeof entry.answer === "string") {
      const words = entry.answer.split(/\s+/).filter((w) => w.length > 3);
      styleKeywords.push(...words.slice(0, 3));
    }
  }

  return {
    prompt,
    negativePrompt: negativePrompt || undefined,
    metadata: {
      confidence: contextState.confidence,
      completeness: contextState.isComplete ? 1.0 : contextState.confidence,
      styleKeywords: styleKeywords.slice(0, 10),
      technicalNotes: "Generated using TypeScript fallback builder",
    },
    fromDSPy: false,
  };
}

/**
 * Cache key for prompt caching
 */
export function getPromptCacheKey(params: {
  contextState: ContextState;
  service?: string | null;
  useCase: string;
  previousPrompt?: string | null;
}): string {
  const { contextState, service, useCase, previousPrompt } = params;
  
  // Create a hash-like key from context state
  const entriesKey = contextState.entries
    .map((e) => `${e.stepId}:${JSON.stringify(e.answer)}`)
    .join("|");
  
  return `${useCase}:${service || "general"}:${contextState.confidence.toFixed(2)}:${previousPrompt || ""}:${entriesKey}`;
}
